name: API license version checker
on:
    pull_request:
        paths:
            - 'src/VERSION'
            - 'api/api/spec/spec.yaml'
    push:

jobs:
    check_license_version:
        name: Check the API license version
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Get VERSION major and minor
            run: |
              echo ${github.ref_name}